"""
Django settings for pattern_service project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DEBUG = False

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pattern_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pattern_service.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Default DB path
default_path = BASE_DIR / "db.sqlite3"

# Use environment variable if set, else default
env_path = os.getenv("SQLITE_PATH")
db_path = Path(env_path) if env_path else default_path

# Ensure DB directory exists
db_path.parent.mkdir(parents=True, exist_ok=True)

# Database configuration
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(db_path),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

DISPATCHER_CONFIG = {
    "version": 2,
    "service": {
        "main_kwargs": {"node_id": "pattern-service-a"},
        "process_manager_kwargs": {
            "preload_modules": ["pattern_service.core.tasks.hazmat"]
        },
    },
    "brokers": {
        "pg_notify": {
            "config": {
                "conninfo": (
                    "dbname=pattern_db user=pattern password=pattern123 "
                    "host=postgres port=5432 application_name=dispatcher_pattern_service"
                )
            },
            "sync_connection_factory": "dispatcherd.brokers.pg_notify.connection_saver",
            "channels": ["pattern-service-tasks"],
            "default_publish_channel": "pattern-service-tasks",
        },
        "socket": {"socket_path": "pattern_service_dispatcher.sock"},
    },
    "publish": {"default_control_broker": "socket", "default_broker": "pg_notify"},
}

# Base URL of your AAP service
URL = "http://localhost:44926"  # or your default URL

# Whether to verify SSL certificates (True or False)
VALIDATE_CERTS = False

# Default username and password for authentication
USERNAME = "admin"
PASSWORD = "your_default_password_here"
