FROM registry.access.redhat.com/ubi9/ubi:latest

WORKDIR /app

COPY requirements/requirements.txt .

RUN dnf install python3-pip -y

RUN python3 -m pip install --no-cache-dir -r requirements.txt

ADD core /app/core

ADD pattern_service /app/pattern_service

COPY manage.py .

RUN python3 manage.py migrate

EXPOSE 8000

CMD ["python3", "/app/manage.py", "runserver", "0.0.0.0:8000", "--noreload"]