FROM registry.access.redhat.com/ubi9/ubi:latest

WORKDIR /app

COPY requirements/requirements.txt .

RUN dnf install python3-pip -y

RUN python3 -m pip install --no-cache-dir -r requirements.txt

ADD core /app/core

ADD pattern_service /app/pattern_service

# Make pattern_service directory writable
RUN chmod -R a+rw /app/pattern_service

COPY manage.py .

EXPOSE 5000

# Run migration at container start time
CMD ["sh", "-c", "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:5000"]
