FROM registry.access.redhat.com/ubi9/ubi:latest

WORKDIR /app

COPY requirements/requirements.txt .

RUN dnf install python3.11 python3.11-pip -y

RUN python3.11 -m pip install --no-cache-dir -r requirements.txt

ADD core /app/core

ADD pattern_service /app/pattern_service

COPY manage.py .

EXPOSE 5000

ENV SQLITE_PATH=/tmp/db.sqlite3

CMD ["sh", "-c", "python3.11 manage.py migrate && python3.11 manage.py runserver 0.0.0.0:5000"]
