# Generated by Django 4.2.22 on 2025-06-25 17:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pattern",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The date/time this resource was created.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pattern",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="The user who created this resource.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pattern",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, help_text="The date/time this resource was created."
            ),
        ),
        migrations.AddField(
            model_name="pattern",
            name="modified_by",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="The user who last modified this resource.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modified+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="automation_id",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="controllerlabel",
            name="label_id",
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="pattern",
            name="collection_version_uri",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pattern",
            name="pattern_definition",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patterninstance",
            name="controller_ee_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patterninstance",
            name="controller_project_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patterninstance",
            name="organization_id",
            field=models.PositiveBigIntegerField(),
        ),
    ]
