# Generated by Django 4.2.23 on 2025-06-26 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_pattern_created_pattern_created_by_pattern_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.')),
                (
                    'status',
                    models.CharField(
                        choices=[('Initiated', 'Initiated'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=20
                    ),
                ),
                ('details', models.JSONField(blank=True, null=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text='The user who created this resource.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_created+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modified_by',
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text='The user who last modified this resource.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modified+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
