# Generated by Django 4.2.23 on 2025-08-05 19:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Initiated", "Initiated"),
                    ("Running", "Running"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                ],
                db_index=True,
                default="Initiated",
                max_length=20,
            ),
        ),
    ]
