# Generated by Django 4.2.23 on 2025-08-12 11:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_task_updated_at_alter_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Initiated", "Initiated"),
                    ("Running", "Running"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                ],
                max_length=20,
            ),
        ),
    ]
