# Generated by Django 4.2.23 on 2025-08-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_task_updated_at_alter_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="updated_at",
        ),
    ]
