x-environment: &common-env
  POSTGRESQL_PORT: 5432
  POSTGRESQL_DATABASE: pattern
  POSTGRESQL_USER: pattern
  POSTGRESQL_PASSWORD: pattern123
  PYTHON_BIN: python3.11

services:
  postgres:
    image: quay.io/sclorg/postgresql-15-c9s:latest
    environment: *common-env
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/pgsql/data'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", postgres, "-d", "$$POSTGRESQL_DATABASE"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  dispatcherd:
    image: localhost/dispatcherd
    environment: *common-env
    build:
      context: ../../
      dockerfile: tools/docker/Dockerfile
      target: dispatcher-image
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  pattern-service-api:
    image: localhost/pattern-service-api
    environment:
      <<: *common-env
    build:
      context: ../../
      dockerfile: tools/docker/Dockerfile
      target: pattern-service-image
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      dispatcherd:
        condition: service_started
    healthcheck:
      test: ['CMD', 'curl', '-q', 'http://localhost:5000/ping/']
      interval: 30s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: {}
